export default {
  data() {
    return {
      unitList: {
        NaN: [],
        APC: [
          { key: "mgPcm", val: "mg/m³" },
          { key: "ppb", val: "ppb" },
          { key: "ppm", val: "ppm" },
          { key: "ugPcm", val: "μg/m³" },
        ],
        EN: [{ key: "db", val: "db" }],
        HU: [{ key: "percentage", val: "%RH" }],
        IL: [{ key: "lx", val: "Lx" }],
        NOC: [
          { key: "none", val: "" },
          { key: "numberCount", val: "个" },
          { key: "timeCount", val: "次" },
        ],
        TEM: [
          { key: "dC", val: "℃" },
          { key: "dF", val: "℉" },
        ],
        ZG_ABSOLUTE_HUMIDITY: [{ key: "ah_gPcm", val: "g/m³" }],
        ZG_AIR_RELATES: [
          { key: "ar_ACH", val: "ACH" },
          { key: "ar_C_F_M", val: "CFM" },
          { key: "ar_cfm", val: "cfm" },
          { key: "ar_cmPh", val: "m³/h" },
          { key: "ar_cmPhp", val: "m³/:h·p" },
          { key: "ar_cmPs", val: "m³/s" },
          { key: "ar_timeCountPh", val: "次/h" },
        ],
        ZG_ANGLE: [
          { key: "a_du", val: "°" },
          { key: "a_fen", val: "'" },
          { key: "a_gon", val: "gon" },
          { key: "a_miao", val: '"' },
          { key: "a_mrad", val: "mrad" },
          { key: "a_rad", val: "rad" },
        ],
        ZG_AREA: [
          { key: "a_acre", val: "acre" },
          { key: "a_are", val: "are" },
          { key: "a_ha", val: "ha" },
          { key: "a_scm", val: "cm²" },
          { key: "a_sdm", val: "dm²" },
          { key: "a_skm", val: "k㎡" },
          { key: "a_sm", val: "㎡" },
          { key: "a_smm", val: "mm²" },
          { key: "a_sqFt", val: "sq.ft" },
          { key: "a_sqIn", val: "sq.in" },
          { key: "a_sqMi", val: "sq.mi" },
          { key: "a_sqYd", val: "sq.yd" },
        ],
        ZG_BRIGHTNESS: [{ key: "b_cdPsm", val: "cd/m²" }],
        ZG_DENSITY: [
          { key: "d_gPccm", val: "g/cm³" },
          { key: "d_gPcdm", val: "g/dm³" },
          { key: "d_gPcm", val: "g/m³" },
          { key: "d_gPl", val: "g/l" },
          { key: "d_kgPccm", val: "kg/cm³" },
          { key: "d_kgPcdm", val: "kg/dm³" },
          { key: "d_kgPcm", val: "kg/m³" },
        ],
        ZG_ELECTRIC: [
          { key: "e_A", val: "A" },
          { key: "e_mA", val: "mA" },
          { key: "e_mV", val: "mV" },
          { key: "e_uA", val: "μA" },
          { key: "e_uV", val: "μV" },
          { key: "e_V", val: "V" },
          { key: "e_VA", val: "V·A" },
        ],
        ZG_ENERGY: [
          { key: "e_btu", val: "btu" },
          { key: "e_cal", val: "cal" },
          { key: "e_ftlb", val: "ft·lb" },
          { key: "e_hph", val: "hp·h" },
          { key: "e_J", val: "J" },
          { key: "e_kcal", val: "kcal" },
          { key: "e_kgm", val: "kg·m" },
          { key: "e_kJ", val: "kJ" },
          { key: "e_kWh", val: "kW·h" },
          { key: "e_psh", val: "ps·h" },
        ],
        ZG_FORCE: [
          { key: "f_dyn", val: "dyn" },
          { key: "f_gf", val: "gf" },
          { key: "f_kgf", val: "kgf" },
          { key: "f_kip", val: "kip" },
          { key: "f_kN", val: "kN" },
          { key: "f_lbf", val: "lbf" },
          { key: "f_N", val: "N" },
          { key: "f_tf", val: "tf" },
        ],
        ZG_FREQUENCY: [
          { key: "f_Hz", val: "Hz" },
          { key: "f_KHz", val: "KHz" },
        ],
        ZG_ILLUMINANCE: [
          { key: "i_fc", val: "fc" },
          { key: "i_lx", val: "lx" },
          { key: "i_SI", val: "SI" },
        ],
        ZG_LENGTH: [
          { key: "l_cm", val: "cm" },
          { key: "l_dm", val: "dm" },
          { key: "l_ft", val: "ft" },
          { key: "l_in", val: "in" },
          { key: "l_km", val: "km" },
          { key: "l_m", val: "m" },
          { key: "l_mi", val: "mi" },
          { key: "l_mm", val: "mm" },
          { key: "l_nm", val: "nm" },
          { key: "l_nmi", val: "nmi" },
          { key: "l_um", val: "µm" },
          { key: "l_yd", val: "yd" },
        ],
        ZG_LIGHT_INTENSITY: [
          { key: "li_cd", val: "cd" },
          { key: "li_mcd", val: "mcd" },
        ],
        ZG_LUMINOUS_FLUX: [{ key: "lf_lm", val: "lm" }],
        ZG_MASS: [
          { key: "m_ct", val: "ct" },
          { key: "m_g", val: "g" },
          { key: "m_kg", val: "kg" },
          { key: "m_lb", val: "lb" },
          { key: "m_mg", val: "mg" },
          { key: "m_oz", val: "oz" },
          { key: "m_point", val: "point" },
          { key: "m_t", val: "t" },
          { key: "m_ug", val: "μg" },
        ],
        ZG_MASS_FLOW: [
          { key: "mf_gPh", val: "g/h" },
          { key: "mf_gPmin", val: "g/min" },
          { key: "mf_gPs", val: "g/s" },
          { key: "mf_kgPh", val: "kg/h" },
          { key: "mf_kgPmin", val: "kg/min" },
          { key: "mf_kgPs", val: "kg/s" },
        ],
        ZG_POLLUTION: [
          { key: "p_gPcm", val: "m³" },
          { key: "p_gPs", val: "g/s" },
          { key: "p_pciPl", val: "pCi/L" },
        ],
        ZG_POWER: [
          { key: "p_BtuPs", val: "Btu/s" },
          { key: "p_ftlbPs", val: "ft·lb/s" },
          { key: "p_hp", val: "hp" },
          { key: "p_JPs", val: "J/s" },
          { key: "p_kcalPs", val: "kcal/s" },
          { key: "p_kgmPs", val: "kg·m/s" },
          { key: "p_kW", val: "kW" },
          { key: "p_M_W", val: "MW" },
          { key: "p_mW", val: "mW" },
          { key: "p_NmPs", val: "N·m/s" },
          { key: "p_ps", val: "ps" },
          { key: "p_W", val: "W" },
        ],
        ZG_PRESSURE: [
          { key: "p_atm", val: "atm" },
          { key: "p_bar", val: "bar" },
          { key: "p_dynPscm", val: "dyn/cm²" },
          { key: "p_hPa", val: "hPa" },
          { key: "p_inHg", val: "in.Hg" },
          { key: "p_kgfPcm2", val: "kgf/cm2" },
          { key: "p_kgfPscm", val: "kgf/cm²" },
          { key: "p_kgfPsm", val: "kgf/m²" },
          { key: "p_kPa", val: "kPa" },
          { key: "p_mbar", val: "mbar" },
          { key: "p_mmH2O", val: "mmH2O" },
          { key: "p_mmHg", val: "mmHg" },
          { key: "p_MPa", val: "MPa" },
          { key: "p_pa", val: "Pa" },
          { key: "p_psf", val: "psf" },
          { key: "p_psi", val: "psi" },
          { key: "p_torr", val: "Torr" },
        ],
        ZG_RADON_CONTENT: [
          { key: "rc_bqPl", val: "Bq/L" },
          { key: "rc_pCiPl", val: "pCi/L" },
        ],
        ZG_SIGNAL_STRENGTH: [{ key: "ss_dBm", val: "dBm" }],
        ZG_SOIL_MOISTURE: [
          { key: "sm_kpa", val: "kPa" },
          { key: "sm_percentage", val: "%" },
        ],
        ZG_SOUND: [
          { key: "s_dB", val: "dB" },
          { key: "s_dBA", val: "dBA" },
        ],
        ZG_SPEED: [
          { key: "s_inPs", val: "in/s" },
          { key: "s_kmPh", val: "km/h" },
          { key: "s_kmPs", val: "km/s" },
          { key: "s_mach", val: "mach" },
          { key: "s_milePh", val: "mile/h" },
          { key: "s_mPs", val: "m/s" },
        ],
        ZG_TIME: [
          { key: "t_d", val: "d" },
          { key: "t_h", val: "h" },
          { key: "t_min", val: "min" },
          { key: "t_ms", val: "ms" },
          { key: "t_ns", val: "ns" },
          { key: "t_s", val: "s" },
          { key: "t_us", val: "μs" },
          { key: "t_week", val: "week" },
          { key: "t_yr", val: "yr" },
        ],
        ZG_VOLUME: [
          { key: "v_ccm", val: "cm³" },
          { key: "v_cdm", val: "dm³" },
          { key: "v_cl", val: "cl" },
          { key: "v_cm", val: "m³" },
          { key: "v_cmm", val: "mm³" },
          { key: "v_cuFt", val: "cuft" },
          { key: "v_cuIn", val: "cuin" },
          { key: "v_dl", val: "dl" },
          { key: "v_l", val: "l" },
          { key: "v_ml", val: "ml" },
          { key: "v_ukGal", val: "ukgal" },
          { key: "v_ul", val: "ul" },
          { key: "v_usGal", val: "usgal" },
        ],
        ZG_VOLUME_FLOW: [
          { key: "vf_ccmPmin", val: "sccm" },
          { key: "vf_cftPh", val: "ft³/h" },
          { key: "vf_cftPmin", val: "ft³/min" },
          { key: "vf_cftPs", val: "ft³/s" },
          { key: "vf_cmPh", val: "m³/h" },
          { key: "vf_cmPmin", val: "m³/min" },
          { key: "vf_cmPs", val: "m³/s" },
          { key: "vf_LPh", val: "L/h" },
          { key: "vf_LPmin", val: "L/min" },
          { key: "vf_LPs", val: "L/s" },
        ],
        ZG_WATER_TURBIDITY: [{ key: "w_mgPl", val: "mg/L" }],
        ZG_WIND_SPEED: [{ key: "ws_mPs", val: "m/s" }],
      } as any,
    };
  },
};
